name: Dependency Change 
on:
  workflow_dispatch: # Mostly for testing
  pull_request_target:
    # paths: # Only run when there are changes to dependencies
    #   - './node/go.mod'
    #   - './node/go.sum'
    types: [opened,edited]
permissions:
  pull-requests: write # Needs to read the contents of PRs

jobs: 
  run-on-mod: 
    runs-on: ubuntu-24.04
    steps:
      - name: Add comment to PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authenticate GitHub CLI via GITHUB TOKEN
          PR_NUMBER: ${{ github.event.number }}     # Get PR number from the event payload
          COMMENT_BODY: "Dependency has been upgraded. This needs to be reviewed manually by Asymmetric Research."
        run: |
          echo "Commenting on PR #$PR_NUMBER"
          gh pr comment "$PR_NUMBER" --body "$COMMENT_BODY"